#!/usr/bin/env python3

import json
from pathlib import Path

# -----------------------------
# Load current investigation
# -----------------------------
with open("data/current_case.json", "r", encoding="utf-8") as f:
    case = json.load(f)

# -----------------------------
# Evidence summary (generated by C#)
# -----------------------------
evidence_summary = ""

summary_file = Path("reconstruction/evidence_summary.md")

if summary_file.exists():
    evidence_summary = summary_file.read_text(encoding="utf-8")
else:
    evidence_summary = "_Evidence summary unavailable._"

# -----------------------------
# Build report
# -----------------------------
report = f"""# Digital Forensic Summary

## Investigation Overview

| Item | Value |
|------|-------|
| Case ID | {case["case_id"]} |
| Operation | {case["operation"]} |
| Classification | {case["classification"]} |
| Severity | {case["severity"]} |
| Status | {case["status"]} |
| Lead Analyst | {case["lead_analyst"]} |

---

## Operational Context

The current investigation involves suspected unauthorized activity affecting protected
biomedical infrastructure. Analysts are conducting structured forensic acquisition,
artifact validation, evidence correlation, and investigative reconstruction to determine
scope, attribution, and operational impact.

---

## Technical Assessment

Threat Family:

**{case["threat_family"]}**

Affected Platform:

**{case["affected_platform"]}**

Device Family:

**{case["device_family"]}**

Network Zone:

**{case["network_zone"]}**

Vendor:

**{case["vendor"]}**

Firmware Version:

**{case["firmware_version"]}**

---

## Risk Assessment

| Metric | Value |
|---------|------:|
| Confidence | {case["confidence"]}% |
| Risk Score | {case["risk_score"]} |
| Evidence Items | {case["evidence_count"]} |
| Indicators | {case["ioc_count"]} |
| Affected Assets | {case["affected_assets"]} |

---

## Analyst Assessment

{case["assessment"]}

---

## Recommended Response

{case["recommended_action"]}

---

## Evidence Analysis

{evidence_summary}

---

## Investigation Status

Current investigative activity remains ongoing.

No final attribution has been established.

Evidence continues to be collected and validated.

The investigation will remain active pending additional forensic acquisition.

"""

output = Path("reconstruction/forensic_summary.md")

output.write_text(report, encoding="utf-8")

print("Forensic summary updated.")
